name: Build and Publish to GitHub NPM Registry

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@cashmere-cat'
          
      - name: Install dependencies
        run: npm ci
        
      - name: TypeScript check
        run: npm run ts-check
        
      - name: Run tests
        run: npm run test
        
      - name: Run linter
        run: npm run lint
        
      - name: Prettier check
        run: npm run prettier-check
        
      - name: Build package
        run: npm run lib:build
        
      - name: Configure package for GitHub registry
        run: |
          npm pkg set name="@cashmere-cat/ttag"
          npm pkg set repository.url="git+https://github.com/cashmere-cat/ttag.git"
          npm pkg set bugs.url="https://github.com/cashmere-cat/ttag/issues"
          npm pkg set homepage="https://github.com/cashmere-cat/ttag#readme"
          
          echo "@cashmere-cat:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> .npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Update version
        if: github.event_name == 'workflow_dispatch'
        run: npm version ${{ github.event.inputs.version }} --no-git-tag-version
        
      - name: Publish to GitHub NPM Registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}